paths:
  heatwave: "/home/benjamin/DLESyM_test/outputs/region_latents_heatwave.zarr"
  no_heatwave: "/home/benjamin/DLESyM_test/outputs/region_latents_nonheatwave.zarr"
  clim_stats: "/home/benjamin/DLESyM_test/outputs/clim_stats.nc"
  output_dir: "./outputs/centroid"
  metrics: "./outputs/centroid/centroid_metrics.csv"

analysis:
  var: "encoder_l2"
  level: 2
  rolling_period: 1


xconfig:
  _target_: instantonanalysis.instanton.schemas.xconfig.XConfigHealPix
  time_dim: time
  channel_dim: channel_l2
  face_dim: face
  height_dim: height_l2
  width_dim: width_l2
