paths:
  heatwave: "/home/benjamin/DLESyM_test/outputs/region_latents_heatwave.zarr"
  no_heatwave: "/home/benjamin/DLESyM_test/outputs/region_latents_nonheatwave.zarr"
  output: "./outputs/pca/pca_plot_l0.jpg"
  metrics: "./outputs/pca/level_metrics.csv"

analysis:
  var: "encoder_l0"
  level: 0
  batch_size: null


xconfig:
  _target_: instantonanalysis.instanton.schemas.xconfig.XConfigHealPix
  time_dim: time
  channel_dim: channel_l0
  face_dim: face
  height_dim: height_l0
  width_dim: width_l0
