defaults:
  - /variables@variables.t2m: t2m
  - /variables@variables.z500: z500
  - /locations@locations.paris: paris
  - spatial: healpix
  - _self_

nside: 64

paths:
  data_root: "./data"
  filenames: ["closest_neighbours", "series_obs", "composite_anomalies", "normalised_var_hat"]
  results_root: "./outputs/healpix"
  climate_mean: "climate_mean_atmos_hpx64_100year.zarr"


analysis:
  rolling_periods: [1, 5]
  select_months: [6, 8]
  quantiles: [0.75, 0.95, 0.99, 0.999]

xconfig:
  time_dim: "step"
  rolling_period: "rolling_period"
  quantile: "quantile"
  lag: "lag"
  event: "event"
  