# @package _global_
defaults:
    - _base_spatial

xconfig:
  _target_: instantonanalysis.instanton.schemas.xconfig.XConfigLonLat
  lon_dim: "lon"
  lat_dim: "lat"

box: ${latlon_from_cfg:${locations.box}}