defaults:
    - _base_location
    - /season@season: djf
    - _self_

name: "rio"
output_folder: "/rio"
box:
  lon_min: -45.0
  lon_max: -42.5
  lat_min: -21.8
  lat_max: -22.8
  lon_sys: "EAST_WEST"
  lat_sys: "NORTH_SOUTH"
domain:
  name: "south_america"
  box:
    lon_min: -110
    lon_max: 0
    lat_min: -55
    lat_max: 5
    lon_sys: "EAST_WEST"
    lat_sys: "SOUTH_NORTH"
  xticks: [-100, -75, -50, -25, 0]
  xtick_labels: ["100°W", "75°W", "50°W", "25°W", "0°"]
  yticks: [-50, -35, -20, -5]
  ytick_labels: ["50°S", "35°S", "20°S", "5°S"]
